server:
  port: 9000

spring:
  application:
    name: front-service
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: ${GOOGLE_OAUTH_CALLBACK_URL}
            authorization-grant-type: authorization_code
            client-name: Google
            provider: google

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
            redirect-uri: ${KAKAO_OAUTH_CALLBACK_URL}
            authorization-grant-type: authorization_code
            client-name: Kakao
            provider: kakao

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - name
              - nickname
              - mobile
            redirect-uri: ${NAVER_OAUTH_CALLBACK_URL}
            authorization-grant-type: authorization_code
            client-name: Naver
            provider: naver

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

sandit:
  edge-service-url: ${EDGE_SERVICE_URL}
  token-redirect-url: ${TOKEN_REDIRECT_URL}

oauth:
  state: ${OAUTH_STATE:1234}  # 필요한 경우 기본값 지정
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_OAUTH_CALLBACK_URL}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_OAUTH_CALLBACK_URL}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_OAUTH_CALLBACK_URL}

kakao:
  rest:
    api-key: ${KAKAO_REST_API_KEY}

app:
  websocket:
    url: ${WEBSOCKET_URL}

portone:
  api:
    key: ${PORTONE_API_KEY}
    secret: ${PORTONE_API_SECRET}
