apiVersion: v1
kind: Service
metadata:
  name: front-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: himedia-a.com.,www.himedia-a.com.
spec:
  type: LoadBalancer #CLB로 진행 ALB는 ingress필요함
  selector:
    app: front-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000