apiVersion: v1
kind: Service
metadata:
  name: front-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: himedia-a.com.
spec:
  type: LoadBalancer
  selector:
    app: front-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9000